default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: foundit_development

test:
  <<: *default
  database: foundit_test

production:
  <<: *default
  database: foundit_production